# version: "3.8"
services:
  mongo-one:
    image: dsylvester/davis-mongo-community:latest
    ports:
      - "3500:27017"
    networks:
      - davis-demo-network
    volumes:
      - mongo-data-volume:/data/db1
    environment:
      MONGO_ADMIN_PASSWORD: /run/secrets/mongo-admin-password
    # command: ["/usr/bin/mongosh --file /var/mongo/create-admin-account.js"]
    secrets:
      - mongo-admin-password

  mongo-two:
    image: dsylvester/davis-mongo-community:latest
    ports:
      - "3520:27017"
    networks:
      - davis-demo-network     
    volumes:
      - mongo-data-volume:/data/db2
    environment:
      MONGO_ADMIN_PASSWORD: /run/secrets/mongo-admin-password
    # command: ["mongosh < /var/mongo/create-admin-account.js"]
    secrets:
      - mongo-admin-password
    depends_on:
      - mongo-one

  mongo-three:
    image: dsylvester/davis-mongo-community:latest
    ports:
      - "3530:27017"
    networks:
      - davis-demo-network
    volumes:
      - mongo-data-volume:/data/db3
    environment:
      MONGO_ADMIN_PASSWORD: /run/secrets/mongo-admin-password
    # command: ["mongosh < /var/mongo/create-admin-account.js"]
    secrets:
      - mongo-admin-password
    depends_on:
      - mongo-one

networks:
  davis-demo-network:
    driver: bridge
    name: davis-demo-network
    ipam:
      driver: default
      config:
        - subnet: "172.16.6.0/24"

volumes:
  mongo-data-volume:
    name: mongo-data-volume

secrets:
  mongo-admin-password:
    environment: "MONGO_ADMIN_PASSWORD"