FROM ubuntu:latest

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install gnupg curl -y

RUN curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
    gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor

RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list

RUN apt-get update

RUN apt-get install -y mongodb-org

RUN mkdir -p /data/db

COPY mongod.conf /etc/mongod.conf

EXPOSE 27017

# ENTRYPOINT [ "/usr/bin/mongod",  "-f",  "/etc/mongod.conf" ]

#  &  /usr/bin/mongosh < /seed.js

#ENTRYPOINT ["/bin/bash", "-c", "postgres & psql -U myuser -d mydb -c 'CREATE TABLE IF NOT EXISTS test (id SERIAL PRIMARY KEY, name VARCHAR(255))'"]
CMD "/usr/bin/mongod -f /etc/mongod.conf"
